//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clase_de_datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cita
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cita()
        {
            this.SeguimientoTratamiento = new HashSet<SeguimientoTratamiento>();
        }
    
        public int CitaId { get; set; }
        public string DNI_pa { get; set; }
        public string DNI_odo { get; set; }
        public System.DateTime Fecha { get; set; }
        public int Hora { get; set; }
        public int CasoId { get; set; }
    
        public virtual CasoClinico CasoClinico { get; set; }
        public virtual Odontologo Odontologo { get; set; }
        public virtual Paciente Paciente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SeguimientoTratamiento> SeguimientoTratamiento { get; set; }
    }
}
