//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clase_de_datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Odontologo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Odontologo()
        {
            this.Cita = new HashSet<Cita>();
        }
    
        public string DNI_odo { get; set; }
        public string Nombre { get; set; }
        public string Especialidad { get; set; }
        public string Turno { get; set; }
        public string Celular { get; set; }
        public int UsuarioId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cita> Cita { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
