//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa_de_datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CasoClinico
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CasoClinico()
        {
            this.Cita = new HashSet<Cita>();
        }
    
        public int CasoId { get; set; }
        public int SeguimientoId { get; set; }
        public int Hora { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public string EstadoPaciente { get; set; }
        public string Diagnostico { get; set; }
        public string Observacion { get; set; }
    
        public virtual SeguimientoTratamiento SeguimientoTratamiento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cita> Cita { get; set; }
    }
}
