//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa_de_datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SnowDentEntities : DbContext
    {
        public SnowDentEntities()
            : base("name=SnowDentEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Cita> Cita { get; set; }
        public DbSet<Odontologo> Odontologo { get; set; }
        public DbSet<Paciente> Paciente { get; set; }
        public DbSet<Recepcionista> Recepcionista { get; set; }
        public DbSet<SeguimientoTratamiento> SeguimientoTratamiento { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
