//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa_de_datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SnowDentEntities : DbContext
    {
        public SnowDentEntities()
            : base("name=SnowDentEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CasoClinico> CasoClinico { get; set; }
        public virtual DbSet<Cita> Cita { get; set; }
        public virtual DbSet<Odontologo> Odontologo { get; set; }
        public virtual DbSet<Paciente> Paciente { get; set; }
        public virtual DbSet<Recepcionista> Recepcionista { get; set; }
        public virtual DbSet<SeguimientoTratamiento> SeguimientoTratamiento { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    }
}
