//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa_de_datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Odontologo
    {
        public Odontologo()
        {
            this.Cita = new HashSet<Cita>();
            this.SeguimientoTratamiento1 = new HashSet<SeguimientoTratamiento>();
        }
    
        public string DNI_odo { get; set; }
        public string Nombre { get; set; }
        public string Especialidad { get; set; }
        public string Turno { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public Nullable<int> ProgramarControl { get; set; }
    
        public virtual ICollection<Cita> Cita { get; set; }
        public virtual SeguimientoTratamiento SeguimientoTratamiento { get; set; }
        public virtual ICollection<SeguimientoTratamiento> SeguimientoTratamiento1 { get; set; }
    }
}
