//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa_de_datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recepcionista
    {
        public string DNI_re { get; set; }
        public string Username { get; set; }
        public int CitaId { get; set; }
        public string Correo { get; set; }
        public string Nombre { get; set; }
    
        public virtual Cita Cita { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
