//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa_de_datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeguimientoTratamiento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SeguimientoTratamiento()
        {
            this.CasoClinico = new HashSet<CasoClinico>();
        }
    
        public int SeguimientoId { get; set; }
        public int CitaId { get; set; }
        public System.DateTime Fecha { get; set; }
        public int Hora { get; set; }
        public System.DateTime FechaProximaCita { get; set; }
        public string Estado { get; set; }
        public string Evolucion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CasoClinico> CasoClinico { get; set; }
        public virtual Cita Cita { get; set; }
    }
}
