//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa_de_datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeguimientoTratamiento
    {
        public SeguimientoTratamiento()
        {
            this.Odontologo = new HashSet<Odontologo>();
            this.Recepcionista = new HashSet<Recepcionista>();
        }
    
        public int SeguimientoId { get; set; }
        public int CitaId { get; set; }
        public string DNI_odo { get; set; }
        public System.DateTime Fecha { get; set; }
        public int Hora { get; set; }
        public string TipoTratamiento { get; set; }
        public string EstadoTratamiento { get; set; }
        public string Diagnostico { get; set; }
        public string Observacion { get; set; }
    
        public virtual Cita Cita { get; set; }
        public virtual ICollection<Odontologo> Odontologo { get; set; }
        public virtual Odontologo Odontologo1 { get; set; }
        public virtual ICollection<Recepcionista> Recepcionista { get; set; }
    }
}
